export enum CustomErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  ADMIN_CREATE_FAILED = "ADMIN_CREATE_FAILED",
  ADMIN_GET_USER_FAILED = "ADMIN_GET_USER_FAILED",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
  NOT_FOUND = "NOT_FOUND",
  INVALID_REFERENCE = "INVALID_REFERENCE",
}
